version: '3.8'
services:
    tensorflow:
        build: ../services/classification
        ports:
            - '8888:8888'
        volumes:
            - ../services/classification:/dnet-classification-service
