version: '3.8'
services:
    tensorflow:
        build: ../services/classification
        ports:
            - '8888:8888'
        volumes:
            - ../services/classification:/dnet-classification-service

    database:
        image: mysql
        container_name: database
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: core_api
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ../services/mysql:/var/lib/mysql
        ports:
            - '3306:3306'

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8081
        depends_on:
            - database

    core-api:
        image: khromov/alpine-nginx-php8
        container_name: core-api
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '../services/core-api:/var/www/html'
        depends_on:
            - database
            # - redis
