version: '3.8'
services:
    core-api:
        image: khromov/alpine-nginx-php8
        container_name: core_api
        ports:
            - '${APP_PORT:-8090}:8080'
        volumes:
            - ../services/core-api:/var/www/html
        depends_on:
            - app-database
            # - redis

    app-database:
        image: postgres
        container_name: app_database
        ports:
            - '5432:5432'
        volumes:
            - ./app-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    data-curation:
        build: ./data-curation
        container_name: data_curation
        ports:
            - '8091:8080'
        volumes:
            - ../services/data-curation:/data-curation
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        depends_on:
            - ml-database

    ml-database:
        image: postgres
        container_name: ml_database
        ports:
            - '5433:5432'
        volumes:
            - ./ml-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    ml-classification:
        build: ./data-classification
        container_name: ml_classification
        ports:
            - '8888:8888'
        volumes:
            - ../services/data-classification:/tensorflow
        depends_on:
            - ml-database
